// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PointsLookup.Data;

namespace PointsLookup.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210118042955_SeedStudentsToTable")]
    partial class SeedStudentsToTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PointsLookup.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("BiologicalScores")
                        .HasColumnType("float");

                    b.Property<double>("ChemiscalScores")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<double>("EnglishScores")
                        .HasColumnType("float");

                    b.Property<string>("IdentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LiteratureScores")
                        .HasColumnType("float");

                    b.Property<double>("MathScores")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PhysicalScores")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BiologicalScores = 8.0,
                            ChemiscalScores = 4.0,
                            DateOfBirth = new DateTime(2001, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnglishScores = 7.2999999999999998,
                            IdentNumber = "732001",
                            LiteratureScores = 7.0,
                            MathScores = 9.0,
                            Name = "Nguyễn Quốc Hải",
                            PhysicalScores = 6.2999999999999998
                        },
                        new
                        {
                            Id = 2,
                            BiologicalScores = 4.0,
                            ChemiscalScores = 6.0,
                            DateOfBirth = new DateTime(2001, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnglishScores = 9.0,
                            IdentNumber = "732002",
                            LiteratureScores = 6.0,
                            MathScores = 8.0,
                            Name = "Lê Thanh Nhàn",
                            PhysicalScores = 5.5
                        },
                        new
                        {
                            Id = 3,
                            BiologicalScores = 4.0,
                            ChemiscalScores = 6.0,
                            DateOfBirth = new DateTime(2001, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnglishScores = 9.0,
                            IdentNumber = "732003",
                            LiteratureScores = 6.0,
                            MathScores = 8.0,
                            Name = "Vũ Hoàng Tú",
                            PhysicalScores = 5.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
