// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PointsLookup.Data;

namespace PointsLookup.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210118145311_AddResultAndStudentToDb")]
    partial class AddResultAndStudentToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("PointsLookup.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<double>("BiologicalScores")
                        .HasColumnType("float");

                    b.Property<string>("CMND_Student")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ChemiscalScores")
                        .HasColumnType("float");

                    b.Property<double>("EnglishScores")
                        .HasColumnType("float");

                    b.Property<string>("IdentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LiteratureScores")
                        .HasColumnType("float");

                    b.Property<double>("MathScores")
                        .HasColumnType("float");

                    b.Property<double>("PhysicalScores")
                        .HasColumnType("float");

                    b.Property<string>("StudentCMND")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StudentCMND");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("PointsLookup.Models.Student", b =>
                {
                    b.Property<string>("CMND")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CMND");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("PointsLookup.Models.Result", b =>
                {
                    b.HasOne("PointsLookup.Models.Student", "Student")
                        .WithMany("Result")
                        .HasForeignKey("StudentCMND");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PointsLookup.Models.Student", b =>
                {
                    b.Navigation("Result");
                });
#pragma warning restore 612, 618
        }
    }
}
